language: objective-c
osx_image: xcode8
script:
    - make test
    - make lint
matrix:
    include:
        - env: SCHEME=KSCrash WORKSPACE=Mac.xcworkspace SDK=macosx10.12
        - env: SCHEME=KSCrashLib WORKSPACE=iOS.xcworkspace SDK=iphonesimulator
        - env: SCHEME=KSCrash-TVOS WORKSPACE=TVOS.xcworkspace SDK=appletvsimulator
