module: Guitar
author: Arthur Ariel Sabintsev
author_url: http://www.sabintsev.com
github_url: https://github.com/artsabintsev/guitar
copyright: "© 2017 [Arthur Ariel Sabintsev](http://www.sabintsev.com)"
clean: true
podspec: Guitar.podspec
