bled_rules:
  - type_name
  - variable_name
  - type_body_length
  - function_body_length
  - file_length
excluded:
  - Examples
  - Tests
type_body_length:
  - 5000 # warning
  - 10000 # error
function_body_length:
  - 5000 # warning
  - 10000 # error
file_length:
  - 5000 # warning
  - 10000 # error
  
