os: osx
language: objective-c
osx_image: xcode9.4
env:
  - PLAT=iOS    DST="OS=11.4,name=iPhone 5s"
  - PLAT=tvOS   DST="OS=11.4,name=Apple TV"
  - PLAT=macOS  DST="arch=x86_64"
cache:
  directories:
  - Carthage
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLAT --verbose
install:
  - xcodebuild -scheme PMKQuartzCore -quiet -destination "$DST" build
script:
  - xcodebuild -scheme PMKQuartzCore -quiet -destination "$DST" test
