# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  keychain_name = "ios-build.keychain"
  keychain_password = ENV["KEY_PASSWORD"]

  create_keychain(
    name: keychain_name,
    password: keychain_password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  import_certificate(
    certificate_path: ".travis/nbl-dis.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: keychain_name,
    keychain_password: keychain_password
  )
  
  lane :fir do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.nbltrustdev.cybex.fir"
    update_app_identifier(
      xcodeproj: "cybexMobile.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "cybexMobile/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.nbltrustdev.cybex.fir" # The App Identifier
    )
    gym(
      xcargs: "-UseNewBuildSystem=YES",
      output_name: "cybex-fir",
      scheme:"cybexMobile",
      workspace:"cybexMobile.xcworkspace",
      configuration:"Release",
      export_method:"ad-hoc",
      output_directory:"~/Documents/ipa",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.nbltrustdev.cybex.fir" => "AdHoc com.nbltrustdev.cybex.fir"
        }
      }
    )
    firim(firim_api_token:"92fc2819f9894e4890c9fd27d4c1d234")
    slack(message: "Successfully distributed cybex to fir, download_url: https://fir.im/7zma ", slack_url:"https://hooks.slack.com/services/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")
  end

  lane :publish do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.nbltrustdev.cybex"
    update_app_identifier(
      xcodeproj: "cybexMobile.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "cybexMobile/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.nbltrustdev.cybex" # The App Identifier
    )
    gym(
      output_name: "cybex-appstore",
      scheme:"cybexMobile",
      workspace:"cybexMobile.xcworkspace",
      configuration:"Release",
      export_method:"app-store",
      output_directory:"~/Documents/ipa",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.nbltrustdev.cybex" => "AppStore #{app_identifier}"
        }
      }
    )
    appstore
    slack(message: "Successfully distributed cybex to appstore", slack_url:"https://hooks.slack.com/services/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")
  end
  
   lane :test do
      xcode_select("/Applications/Xcode.app")
      app_identifier="com.nbltrustdev.cybex"
      update_app_identifier(
        xcodeproj: "cybexMobile.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
        plist_path: "cybexMobile/Info.plist", # Path to info plist file, relative to xcodeproj
        app_identifier: "com.nbltrustdev.cybex" # The App Identifier
      )
      gym(
        output_name: "cybex-testflight",
        scheme:"cybexMobile",
        workspace:"cybexMobile.xcworkspace",
        configuration:"Release",
        export_method:"app-store",
        output_directory:"~/Documents/ipa",
        export_xcargs: "-allowProvisioningUpdates",
        export_options: {
          compileBitcode: false,
          provisioningProfiles: {
            "com.nbltrustdev.cybex" => "AppStore #{app_identifier}"
          }
        }
      )
      upload_to_testflight
      slack(message: "Successfully distributed cybex to testflight", slack_url:"https://hooks.slack.com/services/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")
    end

end
