# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "300"
  ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"
  
  delete_keychain(
    name: "ios-build"
  ) if File.exist? File.expand_path("~/Library/Keychains/ios-build-db")
    
  create_keychain(
    name: "ios-build",
    password: "1",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  import_certificate(
  certificate_path: ".travis/AppleWWDRCA.cer"
  keychain_name: "ios-build",
  keychain_password: "1"
  )

  import_certificate(
    certificate_path: ".travis/nbl-dis.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: "ios-build",
    keychain_password: "1"
  )
  
  lane :fir do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.nbltrustdev.cybex.fir"
    update_app_identifier(
      xcodeproj: "cybexMobile.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "cybexMobile/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.nbltrustdev.cybex.fir" # The App Identifier
    )
    disable_automatic_code_signing(
      path: "cybexMobile.xcodeproj"
    )
    update_project_provisioning(
      xcodeproj: "cybexMobile.xcodeproj",
      profile: ".travis/AdHoc_cybex.mobileprovision", # optional if you use sigh
      build_configuration: "Release",
      target_filter: "cybexMobile", # matches name or type of a target
      code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
    )
    gym(
      xcargs: "-UseNewBuildSystem=YES",
      output_name: "cybex-fir",
      scheme:"cybexMobile",
      project:"cybexMobile.xcodeproj",
      configuration:"Release",
      export_method:"ad-hoc",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.nbltrustdev.cybex.fir" => "iOS Ad Hoc"
        }
      }
    )
    firim(firim_api_token:"92fc2819f9894e4890c9fd27d4c1d234")
    slack(message: "Successfully distributed cybex to fir, download_url: https://fir.im/7zma ", slack_url:"https://hooks.slack.com/services/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")
  end

  lane :publish do
    xcode_select("/Applications/Xcode.app")
    app_identifier="com.nbltrustdev.cybex"
    update_app_identifier(
      xcodeproj: "cybexMobile.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
      plist_path: "cybexMobile/Info.plist", # Path to info plist file, relative to xcodeproj
      app_identifier: "com.nbltrustdev.cybex" # The App Identifier
    )
    disable_automatic_code_signing(
      path: "cybexMobile.xcodeproj"
    )
    update_project_provisioning(
      xcodeproj: "cybexMobile.xcodeproj",
      profile: ".travis/AppStore_cybex.mobileprovision", # optional if you use sigh
      target_filter: "cybexMobile", # matches name or type of a target
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
    )
    gym(
      output_name: "cybex-appstore",
      scheme:"cybexMobile",
      project:"cybexMobile.xcodeproj",
      configuration:"Release",
      export_method:"app-store",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.nbltrustdev.cybex" => "iOS AppStore cybex"
        }
      }
    )
    appstore
    slack(message: "Successfully distributed cybex to appstore", slack_url:"https://hooks.slack.com/services/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")
  end
  
   lane :test do
      xcode_select("/Applications/Xcode.app")
      app_identifier="com.nbltrustdev.cybex"
      update_app_identifier(
        xcodeproj: "cybexMobile.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
        plist_path: "cybexMobile/Info.plist", # Path to info plist file, relative to xcodeproj
        app_identifier: "com.nbltrustdev.cybex" # The App Identifier
      )
      disable_automatic_code_signing(
        path: "cybexMobile.xcodeproj"
      )
      update_project_provisioning(
        xcodeproj: "cybexMobile.xcodeproj",
        profile: ".travis/AppStore_cybex.mobileprovision", # optional if you use sigh
        target_filter: "cybexMobile", # matches name or type of a target
        build_configuration: "Release",
        code_signing_identity: "iPhone Distribution" # optionally specify the codesigning identity
      )
      gym(
        output_name: "cybex-testflight",
        scheme:"cybexMobile",
        project:"cybexMobile.xcodeproj",
        configuration:"Release",
        export_method:"app-store",
        export_options: {
          compileBitcode: false,
          provisioningProfiles: {
            "com.nbltrustdev.cybex" => "iOS AppStore cybex"
          }
        }
      )
      upload_to_testflight(skip_waiting_for_build_processing:true)
      slack(message: "Successfully distributed cybex to testflight", slack_url:"https://hooks.slack.com/services/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")
    end

end
