language: objective-c
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SwiftTheme.xcworkspace
  - SCHEME=SwiftTheme
  - SDK=iphonesimulator11.0
  - DEMO_SCHEME=Demo
  - PLIST_DEMO_SCHEME=PlistDemo
  - OCDEMO_SCHEME=OCDemo
  matrix:
    - DESTINATION="OS=11.0,name=iPhone X"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"
    - DESTINATION="OS=9.0,name=iPhone 6"
    - DESTINATION="OS=8.1,name=iPhone 5"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -workspace "$WORKSPACE" -scheme "$DEMO_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -workspace "$WORKSPACE" -scheme "$PLIST_DEMO_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
  - xcodebuild -workspace "$WORKSPACE" -scheme "$OCDEMO_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
