language: objective-c
cache:
  directories:
  - Lib/vendor/bundle
install:
- (cd Lib && bundle install --path=vendor/bundle --binstubs=vendor/bin)
before_script:
- ./Lib/Scripts/decode_cert.sh || true
- ./Lib/Scripts/add_key.sh || true
script:
- '(cd Lib && travis_retry bundle exec rake $ACTION)'
branches:
  only:
  - master
matrix:
  include:
  - osx_image: xcode10
    env: ACTION=build
  - osx_image: xcode10
    env: ACTION='test:iphonesimulator'
  - osx_image: xcode10
    env: ACTION='test:appletvsimulator'
  - osx_image: xcode10
    env: ACTION='test:macosx'
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - secure: Fw0I2kQLC6j5BxOw7thOuGwTS6B6thpyM2xdF06Turek8TRGyzjU+QGtH1fdhJd03sDaX7LJTwn3wE2ffMTyfy/7uXGNroHJVfBz4yGjEhvL3z93FLWrLrXQqh1s+apWCJcwuE7kVqDUsjg4/HkIBq3nnGhS/nzlYNxacVx01oI=
  - secure: lKWscex7qoKykLXdWZ830mxvnIz27Vz9T4ryb6Ets8H9C58DEWWz/dNqNm8cYIWmTb+xcvPybDwKmggIEvCvumSwI6XtJMfJviQSWpdOg2vIS1LiiILgDLRmpHL8Eb+FXr8MY7PYYc6rnIYp4HvuovnAIgjqUtLZ+vPuL4KEUV4=
