env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release -sdk iphonesimulator -destination "name=iPhone 6s" ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release -sdk appletvsimulator -destination "name=Apple TV" ENABLE_TESTABILITY=YES | xcpretty -c
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release -sdk iphonesimulator -destination "name=iPhone 6s" ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release -sdk appletvsimulator -destination "name=Apple TV" ENABLE_TESTABILITY=YES | xcpretty -c
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      language: generic
      osx_image: xcode9.2
      script:
        - swift build
        - swift test
    - os: osx
      language: generic
      osx_image: xcode9.3
      script:
        - swift build
        - swift test

notifications:
  email: false
