# Jazzy config
module:      Apollo

author:      Apollo GraphQL
author_url:  https://github.com/apollographql
github_url:  https://github.com/apollographql/apollo-ios

theme:       fullwidth
readme:      README.md

hide_documentation_coverage: true
skip_undocumented: true

exclude:
  - Sources/JSONStandardTypeConversions.swift
  - Sources/Utilities.swift

custom_categories:
  - name: Core
    children:
      - ApolloClient
      - GraphQLResult
      - GraphQLError
      - CachePolicy
      - Cancellable
      - GraphQLQueryWatcher

  - name: Networking
    children:
      - NetworkTransport
      - GraphQLResponse
      - HTTPNetworkTransport
      - GraphQLHTTPResponseError

  - name: Store
    children:
      - ApolloStore
      - RecordSet
      - Record
      - CacheKey
      - CacheKeyForObject
      - Reference

  - name: Execution
    children:
      - GraphQLExecutor
      - GraphQLMappable
