language: objective-c
osx_image: xcode10.2

env:
  global:
    - IOS_FRAMEWORK_SCHEME="HandyJSON iOS"
    - OSX_FRAMEWORK_SCHEME="HandyJSON Mac"
    - TVOS_FRAMEWORK_SCHEME="HandyJSON tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="HandyJSON watchOS"
    - IOS_SDK=iphonesimulator12.2
    - OSX_SDK=macosx10.14

before_install:
  - gem install xcpretty --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - echo "Applying fix for rdar://49326587 see https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_1_release_notes?language=objc"
  - sudo mkdir '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift'

  - xcodebuild -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "platform=iOS Simulator,OS=12.0,name=iPhone XS Max" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  - xcodebuild -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "platform=iOS Simulator,OS=11.4,name=iPhone 8" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  - xcodebuild -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "platform=iOS Simulator,OS=10.1,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  - xcodebuild -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  - xcodebuild -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "platform=iOS Simulator,OS=8.1,name=iPhone 5" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

  - xcodebuild -scheme "HandyJSON macOS" test

  - xcodebuild -scheme "HandyJSON tvOS" -destination "platform=tvOS Simulator,OS=12.0,name=Apple TV" test

after_success:
  - bash <(curl -s https://codecov.io/bash)
